### ISSUE TITLE
issue in implementing the limit 

### ISSUE THREAD

**Issue by yash85763** [FahadNoor/py_crunchbase#11]
I am trying to fetch HQ address of a company but I don't understand how to implement the limit in EntityAPI below is the code for reference:

`# Access the organizations API
org_api = pycb.organizations_api()

# Define the cards for organization jobs
cards = Cards.Organization

# Fetch the organization entity data
entity = org_api.get_cards(
    entity_id=Company_2_look_4,
    card_id=cards.headquarters_address, 
    card_field_ids=['country_code', 'headquartered_organization_identifier', 'identifier', 'location_identifiers', 'name', 'postal_code', 'region_code', 'street_1',  'street_2']
).limit(10).execute()`

**Comment by FahadNoor** [comment]
Hi @yash85763. I will update the `get_cards` method to accept limit too as soon as I get some time on my hands. Meanwhile, If you look at the [get_cards](https://github.com/FahadNoor/py_crunchbase/blob/main/py_crunchbase/apis/entities/main.py#L35) method you will see that it's internally using `CardsAPI`. So you can do the same.

```python
from itertools import chain
org_api = pycb.organizations_api()
cards = Cards.Organization

cards_api = (
    org_api.get_cards_api(
        entity_id=Company_2_look_4, card_id=cards.headquarters_address
    )
    .select(
        'country_code',
        'headquartered_organization_identifier',
        'identifier',
        'location_identifiers',
        'name',
        'postal_code',
        'region_code',
        'street_1',
        'street_2',
    )
    .limit(5)
)

cards_list = list(
    chain.from_iterable(
        list(entity.cards.values())[0] for entity in cards_api.iterate()
    )
)
```

I hope this helps.

**Comment by FahadNoor** [comment]
Closing the issue. Feel free to reopen if the problem still exists.

**Comment by yash85763** [comment]
Hi @FahadNoor I tried it, but still not working, can you tell me how can I update the get_cards method for limit?

`from py_crunchbase import PyCrunchbase, Cards
import json
import yaml
from itertools import chain

Company_2_look_4 = 'tesla-motors'

# Initialize PyCrunchbase with the API key
pycb = PyCrunchbase('*************************')

# Access the organizations API
org_api = pycb.organizations_api()

# Define the cards for organization jobs
cards = Cards.Organization

call_limit = 3

# Fetch the organization entity data
cards_api = (org_api.get_cards_api(
    entity_id=Company_2_look_4,
    card_id=cards.press_references).select('activity_entities', 
                    'author',
                    'entity_def_id',
                    'identifier', 
                    'posted_on', 
                    'publisher', 
                    'thumbnail_url', 
                    'title', 
                    'url').limit(10))

cards_list = list(
    chain.from_iterable(
        list(entity.cards.values())[0] for entity in cards_api.iterate()
    )
)`

**Comment by yash85763** [comment]
Hi @FahadNoor I tried it, but still not working, can you tell me how can I update the get_cards method for limit?

```python
from py_crunchbase import PyCrunchbase, Cards
import json
import yaml
from itertools import chain

Company_2_look_4 = 'tesla-motors'

# Initialize PyCrunchbase with the API key
pycb = PyCrunchbase('*************************')

# Access the organizations API
org_api = pycb.organizations_api()

# Define the cards for organization jobs
cards = Cards.Organization

call_limit = 3

# Fetch the organization entity data
cards_api = (org_api.get_cards_api(
    entity_id=Company_2_look_4,
    card_id=cards.press_references).select('activity_entities', 
                    'author',
                    'entity_def_id',
                    'identifier', 
                    'posted_on', 
                    'publisher', 
                    'thumbnail_url', 
                    'title', 
                    'url').limit(10))

cards_list = list(
    chain.from_iterable(
        list(entity.cards.values())[0] for entity in cards_api.iterate()
    )
)
```

**Comment by yash85763** [comment]
Hi @FahadNoor , actually I updated the get_cards() with limit, do you want me to add the small piece in the code?

**Comment by FahadNoor** [comment]
Hi @yash85763, that would be great! Please create a pull request with updated test. Thank you.
